### ISSUE TITLE
Can not run the "install.sh" Syntax error

### ISSUE THREAD

**Issue by M0dred** [vulsio/vulsctl#21]
wget https://github.com/vulsio/vulsctl/blob/master/install-host/install.sh

sudo chmod +x install.sh && ./install.sh 

install.sh: line 7: syntax error near unexpected token `newline'
install.sh: line 7: `<!DOCTYPE html>'

**Comment by Jiab77** [comment]
@M0dred Did you have checked the documentation from here: https://vuls.io/docs/en/install-with-vulsctl-host.html and / or tested this version: https://github.com/vulsio/vulsctl/pull/17

**Comment by shino** [comment]
This issue was closed because it has been inactive.
