### ISSUE TITLE
Database update error when running install-host/update-all.sh

### ISSUE THREAD

**Issue by Jiab77** [vulsio/vulsctl#26]
After having upgraded `vuls` to the latest version (`0.14.1`), I ran the script `install-host/update-all.sh` and during the update process this error has been displayed:

```
INFO[01-04|15:55:12] Initialize Database 
2021-01-04T15:55:12.350+0100	DEBUG	db path: db/trivy.db
2021-01-04T15:55:12.377+0100	DEBUG	git pull
2021-01-04T15:55:14.792+0100	DEBUG	From https://github.com/aquasecurity/vuln-list
 * branch            master     -> FETCH_HEAD
fatal: This operation must be run in a work tree

error in vulnerability DB initialize: error in vulnsrc clone or pull: failed to pull repository: error in git pull: failed to exec: exit status 128
INFO[01-04|15:55:14] Initialize Database 
INFO[01-04|15:55:14] Opening DB.                              db=sqlite3
INFO[01-04|15:55:14] Migrating DB.                            db=sqlite3
```

After some debugging process, the guilty script is `gost.sh` and the issue can be replicated by simply running `./gost.sh --redhat`.

To solve this issue, I had to rename the vulnerabilities folder from `vuln-list` to `vuln-list.old` and re-run the `update-all.sh` script.

Once done, the folder `vuln-list` has been re-created and the error is gone:

```
INFO[01-04|16:10:30] Initialize Database 
2021-01-04T16:10:30.343+0100	DEBUG	db path: db/trivy.db
2021-01-04T16:10:30.401+0100	DEBUG	remove an existed directory
INFO[01-04|16:12:54] Opening DB.                              db=sqlite3
INFO[01-04|16:12:54] Migrating DB.                             db=sqlite3
```

I don't have enough knowledge in `golang` programming to debug the `gost` binary myself unfortunately.

**Comment by Jiab77** [comment]
Folder size difference:

```bash
# After update
du -sh vuln-list
2.7G	vuln-list

# Before update
du -sh vuln-list.old
2.4G	vuln-list.old
```

**Comment by kotakanbe** [comment]
It's working fine in my environment. Please try the latest version. If it recurs, please reopen it.
