### ISSUE TITLE
Hardcoded version in cvedb does not match with latest release of vuls

### ISSUE THREAD

**Issue by sudnonk** [vulsio/vulsctl#39]
Thank you for this great tool.

I found in `install-host/cvedb.sh`, the version of vuls which has `cve.sqlite3.gz` is hardcoded as `v0.13.1`.
https://github.com/vulsio/vulsctl/blob/b1c62acf930a239a7f98c7b7909200c66939b984/install-host/cvedb.sh#L3-L7

In the other hand, the latest released version of vuls with `cve.sqlite3.gz` should be currently `v0.15.10`.
I don't check the code well but this may cause some schema problem.
If you don't have a reason to keep it as `v0.13.1`, I can do a pull request to change this oneline.

Regards,

**Comment by MaineK00n** [comment]
This commit(https://github.com/vulsio/vulsctl/commit/76b5a1c2aeab04db23fecc11817256014c2ab63a#diff-640f4a7b721fe3cabff0aa9d32d8bd55c01e9281bf2d1e2db29a59349ef03065) removes the subject section.
go-cve-dictionary fetches faster, so it is no longer necessary to fetch cve.sqlite3.gz from release.
