### ISSUE TITLE
Scanning & Reporting for Oracle Linux 7.8 fails

### ISSUE THREAD

**Issue by Bazza63** [vulsio/vulsctl#4]
Scanning Oracle 7.8 errors without having sudo enabled for the remote ssh account. Note this does not happen with Red Hat 7.8
Reporting on Oracle 7.8 fails with no OVAl's found.
Testing shows that Oracle is not a valid variable for the following scripts.
update-all.sh
oval.sh
gost.sh

System built using https://vuls.io/docs/en/install-with-docker.html

**Comment by kotakanbe** [comment]
@Bazza63 
Has OVAL for oracle been fetched?
https://github.com/kotakanbe/goval-dictionary#usage-fetch-oval-data-from-oracle

**Comment by kotakanbe** [comment]
@Bazza63 
The oracle oval fetch in oval.sh was not implemented. 
Try changing here to fetch oracle oval.
https://github.com/vulsio/vulsctl/blob/master/oval.sh#L14

If it works, please make a pull request.

**Comment by kotakanbe** [comment]
https://github.com/vulsio/vulsctl/pull/28
