### ISSUE TITLE
OVAL database not working

### ISSUE THREAD

**Issue by michael-antonelli** [vulsio/vulsctl#76]
Hello,

I am experiencing an issue when trying to report on ubuntu hosts with the OVAL db. When I run `oval.sh --ubuntu` I get this warning:

`WARN[07-19|14:43:49] Failed to parse string                   timeformat="[2006-01-02 2006-01-02 15:04:05 2006-01-02 15:04:05 +0000 2006-01-02 15:04:05 UTC]" target string="2023-02-14 17:00:00 CET"`

...but the download seems to finish successfully. 

```
INFO[07-19|15:26:03] Deleting old Definitions...
18665 / 18665 [---------------------------------------------------------------------------------------------------------------------------] 100.00% 9713 p/s
INFO[07-19|15:26:05] Inserting new Definitions...
18665 / 18665 [---------------------------------------------------------------------------------------------------------------------------] 100.00% 3474 p/s
INFO[07-19|15:26:11] Finish                                   Updated=18665
```

When I open the sqlite3 db and inspect the tables they seem to be fully populated. However when I run report.sh I get this message:

```
time="Jul 19 15:09:24" level=info msg="Skip OVAL and Scan with gost alone."
time="Jul 19 15:09:24" level=info msg="[Reboot Required] *******: 0 CVEs are detected with OVAL"
...
No CVE-IDs are found in updatable packages.
1637 installed
```

This is an issue that never occurred in the past and has only cropped up since the oval.sh script was updated.

Thank you,
Mike

**Comment by MaineK00n** [comment]
> I am experiencing an issue when trying to report on ubuntu hosts with the OVAL db. When I run oval.sh --ubuntu I get this warning:

It is a warning due to an unexpected format. I will check and fix it.

> When I open the sqlite3 db and inspect the tables they seem to be fully populated. However when I run report.sh I get this message:

Currently, when reporting Ubuntu in Vuls, OVAL DB is not used, and only Gost DB is used. ( previously OVAL and Gost DB were used together).
